#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/main/packages/wrangler/config-schema.json
name = "jacilandia"
pages_build_output_dir = "dist"
compatibility_date = "2025-02-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "jaci-db"
database_id = "f5dc1c56-f335-4803-becf-136384382cef"

[[r2_buckets]]
binding = "R2"
bucket_name = "jaci-assets"

[vars]
APP_URL = "https://jacilandia.mx"
GOOGLE_CLIENT_ID = "174406118242-vern534bf8oj4iibmk5fhhne7khigd9q.apps.googleusercontent.com"
