#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/main/packages/wrangler/config-schema.json
name = "jacilandia-mx"
pages_build_output_dir = "dist"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB"
database_name = "jaci-db"
database_id = "jaci-db" # Local emulator name

[[r2_buckets]]
binding = "R2"
bucket_name = "jaci-assets"
