#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/main/packages/wrangler/config-schema.json
name = "jacilandia-mx"
pages_build_output_dir = "dist"
compatibility_date = "2025-02-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "jaci-db"
database_id = "67ad713e-1d5e-42a9-8918-9e77b689c0c3"

[[r2_buckets]]
binding = "R2"
bucket_name = "jaci-assets"
